### ISSUE TITLE
Using C++

### ISSUE THREAD

**Issue by Jack-O-Brian** [MuazAlhaidar/Cpp_Shenanigans#1]
why not lisp, or if you want C, use https://www.call-cc.org/

**Comment by MuazAlhaidar** [comment]
no you

**Comment by Jack-O-Brian** [comment]
On Mon, Apr 12, 2021 at 05:12:27PM -0700, MuazAlhaidar wrote:
> Closed #1.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/MuazAlhaidar/Cpp_Shenanigans/issues/1#event-4585117792
No YOU
